# Form implementation generated from reading ui file 'DialogAddPlayer.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 132)
        self.set_player_name_line = QtWidgets.QLineEdit(Dialog)
        self.set_player_name_line.setGeometry(QtCore.QRect(20, 50, 241, 20))
        self.set_player_name_line.setInputMask("")
        self.set_player_name_line.setText("")
        self.set_player_name_line.setObjectName("set_player_name_line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label.setObjectName("label")
        self.set_player_name_btn = QtWidgets.QPushButton(Dialog)
        self.set_player_name_btn.setGeometry(QtCore.QRect(20, 80, 241, 31))
        self.set_player_name_btn.setObjectName("set_player_name_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Set player name:"))
        self.set_player_name_btn.setText(_translate("Dialog", "Done"))
